version: '3'
services:
    proxy:
        restart: unless-stopped
        image: 1fe5200ca6f8
        ports:
            - 80:80/tcp
            - 443:443/tcp
        environment:
            CERTBOT_EMAIL: soujinko@naver.com
            ENVSUBST_VARS: FQDN
            FQDN: ruzan.shop
        volumes:
          - /home/ubuntu/nginx/cache:/etc/nginx/cache
          - /home/ubuntu/nginx/temp:/etc/nginx/temp
          - .:/etc/nginx/
          - ./conf.d:/etc/nginx/conf.d:ro
          - /etc/letsencrypt:/etc/letsencrypt


volumes:
    letsencrypt:
